"""add unsubscribe_token to newsletter_subscribers

Revision ID: c1d7b9ce1707
Revises: b814e9e02ce7
Create Date: 2026-07-25 21:57:44.794166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1d7b9ce1707'
down_revision: Union[str, Sequence[str], None] = 'b814e9e02ce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newsletter_subscribers', sa.Column('unsubscribe_token', sa.String(), nullable=True))
    op.create_index(op.f('ix_newsletter_subscribers_unsubscribe_token'), 'newsletter_subscribers', ['unsubscribe_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_newsletter_subscribers_unsubscribe_token'), table_name='newsletter_subscribers')
    op.drop_column('newsletter_subscribers', 'unsubscribe_token')
    # ### end Alembic commands ###
